[package]
name = "ariadne-macros"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true

[features]
labrinth = []

[lints]
workspace = true
