[package]
name = "ariadne"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
uuid = { workspace = true, features = ["v4", "fast-rng", "serde"] }
serde_bytes.workspace = true
rand.workspace = true
either.workspace = true
chrono = { workspace = true, features = ["serde"] }
serde_cbor.workspace = true

ariadne-macros.workspace = true

[features]
labrinth = ["ariadne-macros/labrinth"]

[lints]
workspace = true
